version: "3.9"

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5001:5001"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7
    container_name: redis-server
