version: '3.9'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # Change this to a strong password
      MYSQL_DATABASE: mydatabase          # Optional: creates a default database
      MYSQL_USER: user                    # Optional: creates a user
      MYSQL_PASSWORD: userpassword        # Password for the above user
    volumes: 
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports: 
      - "8080:8080"
volumes:
 db_data:
