services:
    mongo:
        image: mongo
        container_name: mongo-db 
        restart: always
        ports:
         - "27017:27017"
        volumes:
            - mongo_data:/data/db
    app:
        build: .
        container_name: node-app 
        ports:
            - "3000:3000"
        depends_on:
            - mongo
volumes:
    mongo_data:
